name: Generate Waiver PDFs and Add to Email Queue

on:
  workflow_dispatch:
    inputs:
      family_id:
        description: "Family Tag ID"
        required: true
      parent_email:
        description: "Parent Email"
        required: true
      member_json:
        description: "JSON array of members (name, initials, is_minor, unique_id)"
        required: true

jobs:
  generate-pdfs-and-queue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install pdf-lib

      - name: Write Member JSON to File
        run: echo '${{ github.event.inputs.member_json }}' > members.json

      - name: Generate PDFs for Each Member
        run: |
          node -e "
            const fs = require('fs');
            const { execSync } = require('child_process');
            const members = JSON.parse(fs.readFileSync('members.json', 'utf8'));
            for (const m of members) {
              if (!m.name || !m.initials || !m.unique_id) continue;
              console.log('🖨 Generating for:', m.name);
              execSync(\`node fill.js '\${m.name}' '\${m.initials}' \${m.is_minor} '\${m.unique_id}'\`, { stdio: 'inherit' });
            }
          "

      - name: Commit PDFs
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add filled/*.pdf
          git commit -m "🧾 Add waiver PDFs for ${{ github.event.inputs.family_id }}" || echo "Nothing to commit"
          git pull --rebase
          git push

      - name: Add Family to Email Queue
        run: |
          mkdir -p queue
          node updateStatus.js "$FAMILY_ID" "$PARENT_EMAIL" "$MEMBER_JSON"
        env:
          FAMILY_ID: ${{ github.event.inputs.family_id }}
          PARENT_EMAIL: ${{ github.event.inputs.parent_email }}
          MEMBER_JSON: ${{ github.event.inputs.member_json }}

      - name: Commit updated Email Queue
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add queue/ready_to_email.json
          git commit -m "📩 Queue family ${{ github.event.inputs.family_id }} for email" || echo "Nothing to commit"
          git pull --rebase
          git push
